### ISSUE TITLE
Tools to make metadata

### ISSUE THREAD

**Issue by sudach** [dataware-tools/pydtk#32]
## Description
- メタ情報を生成するツールが必要

## Purpose
- DB(テーブル)に登録するためにメタデータが必要

## 実装方針
- ファイルの拡張子で`pydtk/models`のモデルを選定
- `BaseModel`で`generate_contents_meta`を定義した上で，各モデル内でcontentsのメタ情報を抽出する`generate_contents_meta`を定義

**Comment by sudach** [comment]
[このコミット](https://github.com/dataware-tools/pydtk/commit/97fd0826b7547e73688049c153c91d590729f5e8)で`generate_contents_meta`methodなるものを作ったのですが，以下のようなcontentsしか取得できません．
プロパティらへんの実装が誤っているのでしょうか？ @d-hayashi 

取得できるcontents情報
```
'contents': <property object at 0x7f2262299228>
```


所望のcontents情報
```
'contents': {"columns": ["col1", "col2", "col3"]}
```


ちなみに実行コマンドはこちら
```
$ pwd
/opt/pydtk/pydtk/bin
$ ./make_meta.py  --template sample.json --file sample.csv
```

**Comment by WatanabeToshimitsu** [comment]
僕の方で再現すると下記のようになりました
```
root@f44a424626b9:/opt/pydtk/pydtk/bin# ./make_meta.py  --template sample.json --file sample.csv
WARNING:root:Failed to load models in rosbag.py
WARNING:root:Failed to load models in pointcloud
WARNING:root:Failed to load models in autoware
--Return--
> /opt/pydtk/pydtk/bin/make_meta.py(116)main()->None
-> pdb.set_trace()
(Pdb) l
111         if args.it:
112             meta = make_meta_interactively(template)
113         else:
114             meta = make_meta(args.file, template)
115  
116  ->         pdb.set_trace()
117  
118  
119     if __name__ == "__main__":
120         main()
[EOF]
(Pdb) meta
{'description': 'forecast', 'database_id': 'JERA Forecast', 'record_id': 'test', 'type': 'raw_data', 'path': 'sample.csv', 'content-type': 'text/csv', 'contents': <function GenericCsvModel.generate_contents_meta at 0x7efd47ab86a8>}
(Pdb) meta["contents"]
<function GenericCsvModel.generate_contents_meta at 0x7efd47ab86a8>
```
出力が若干異なるんので参考になるか分かりませんが，少なくともこのような出力になる原因は以下の通りでした

1. 69行目の`MODELS_BY_PRIORITY[priority]`が**クラス**の dict である
2. 56行目が関数自体への参照を代入してしまっている

なので，54行目の
`    contents = model.generate_contents_meta`
を
`    contents = model.generate_contents_meta()`
に変更して関数をコールして，
69行目の
`                return model`
を
`                return model()`
にしてインスタンスを返すようにすると，以下のように想定通り？に出力されるようになりました
```
root@f44a424626b9:/opt/pydtk/pydtk/bin# ./make_meta.py  --template sample.json --file sample.csv
WARNING:root:Failed to load models in rosbag.py
WARNING:root:Failed to load models in pointcloud
WARNING:root:Failed to load models in autoware
None
--Return--
> /opt/pydtk/pydtk/bin/make_meta.py(114)main()->None
-> pdb.set_trace()
(Pdb) meta
{'description': 'forecast', 'database_id': 'JERA Forecast', 'record_id': 'test', 'type': 'raw_data', 'path': 'sample.csv', 'content-type': 'text/csv', 'contents': {'columns': ['col1', 'col2', 'col3']}}
```

**Comment by sudach** [comment]
ありがとうございます！ここがネックだったようです！ @WatanabeToshimitsu 
> `return model()`にしてインスタンスを返す

**Comment by d-hayashi** [comment]
確認するの遅くなって申し訳ないです。
Python の property デコレータの使い方については [このあたり](https://qiita.com/Sylba2050/items/d6f23ac13a0cc5da0c17) を見てもらえると雰囲気が分かるかと思います。

`generate_contents_meta` をプロパティにするのであれば名前は `contents_meta` の方が良いかと。

修正版の様にモデルのオブジェクトを初期化してデータを読み込んだ後にプロパティでそのメタ情報にアクセスするのでも良いと思いますが、 `GenericRosbagModel` 等、 コンテンツが複数存在しうるファイルの場合は、現状 `_load` 関数でコンテンツを1つに絞って読み込んでしまっているので、ファイルに入ってるコンテンツ全部のメタ情報を上手く取り出す方法を考えないといけないかなと思います。

個人的には `generate_contents_meta` 関数を、 `_load` 関数とは別にファイルを読んでメタ情報だけを生成する関数にしてしまったほうが楽かと思ってます。その場合モデルオブジェクトの初期化も不要だと思うので、[こんな感じ](https://github.com/dataware-tools/pydtk/commit/076bfbe5dfa1c3ae854d4fe726ae66615950bcae)のを想像してました。 (コードは適当に書いただけなので多分動かないです)

**Comment by sudach** [comment]
コメントありがとうございます，以下の方針で進めます．
- `generate_contents_meta`はpropertyからmethodへ
- ファイル読み込みは`_load`関数ではないものを実装・利用する

あと，サンプルコードちゃんと動いたので[取り込み](https://github.com/dataware-tools/pydtk/pull/33/commits/2cbebd5dfa8606994aab9dc1d8d71c02ed73530f)ました．

**Comment by sudach** [comment]
一通り実装して2点気になった点があります．
- [この実装](https://github.com/dataware-tools/pydtk/commit/076bfbe5dfa1c3ae854d4fe726ae66615950bcae)の返り値がlistの意図
これまでのmetadataのcontentsの中身ってdict(json)フォーマットだったので．
- `content`引数の用途イメージ

**Comment by d-hayashi** [comment]
返り値をリスト型にしてあったのは完全に僕の勘違いです。。 dictでokだと思います
