### ISSUE TITLE
Add `display_name` of columns

### ISSUE THREAD

**Issue by d-hayashi** [dataware-tools/pydtk#36]
## Purpose
feature request

## Description
メタ情報を DataFrame で出力した際にカラム名を任意のものに変えられるよう、各カラムに対して `name` の他に `display_name` という設定項目を追加する。 また、V4DBHandler の `df` プロパティを参照した際に、各列名を `name` の代わりに `display_name` で表示する

**Comment by d-hayashi** [comment]
@WatanabeToshimitsu 
列名を任意のものに変えられるようにする件ですが、今の `name` を `id` とかにするとバグの原因になる気がするので、単純に `display_name` という設定項目を新たに追加して DataFrame での表示の際にそれを使うという案を考えてみました。
フロント的にはこれでも大丈夫でしょうか？

**Comment by WatanabeToshimitsu** [comment]
フロント的には「DB上でのカラムの識別子（name）」と「 UI 上での表示名（display_name）」が紐づいたデータが受け取れればOKだと考えてるので，問題ないと思います！
現状レコード一覧を表示するために使用されてる /{database_id}/records では df とか record_df？ を返してた気がするので，df が display_name を反映してくれるのも助かります
