### ISSUE TITLE
Listing large amount of metadata is slow

### ISSUE THREAD

**Issue by d-hayashi** [dataware-tools/pydtk#56]
## Purpose
Feature request

## Description
Listing metadata of 3k files with `pydtk db list files` is very slow though `pydtk db list files --parsable` finishes within a reasonable time.
It seems that creating DataFrame in DBHandler is a bottleneck.

## Symtem info [Optional]
- Commit: f8e5d33ccf4839f96c59e40bf202d0a5a9d475cc
- Ubuntu 18
- DB: MongoDB

**Comment by hdl-service** [comment]
@d-hayashi: ![cat image](https://cdn2.thecatapi.com/images/15v.jpg)

<details>

In response to [this](https://github.com/dataware-tools/pydtk/issues/56#issuecomment-849318828):

>/meow


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by hdl-service** [comment]
@d-hayashi: [![dog image](https://random.dog/d4287fd5-ec3f-4816-a8e1-962ee8e86643.jpg)](https://random.dog/d4287fd5-ec3f-4816-a8e1-962ee8e86643.jpg)

<details>

In response to [this](https://github.com/dataware-tools/pydtk/issues/56#issuecomment-849462606):

>/woof


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by sudach** [comment]
This function is taking a long time to return DataFrame.
https://github.com/dataware-tools/pydtk/blob/5a639aae3aa07d65ed6a27f578e8736effc133be/pydtk/db/v4/handlers/meta.py#L277

**Comment by sudach** [comment]
The default value is`--limit=20`, which is a reasonable time if not specified.
